# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b1aa925cd3d48e49beee4d64809f8fa561647ef863f2133b4e6c542be6fc4bcaff23c94281da8027cde5e58ca6959707499ddbd5a7b6866b002fea98f776df

test:
  secret_key_base: abba2bf30477ee6dc8f8febed3f8aad9f85448ae77815ef6fbbba40af20d84ecacabe869517495c916a18a8de988324bce51b12e63fc4b9321de73337b22f581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
